[package]
name = "rust_snitch"
version = "0.1.0"
authors = ["Aleksei Kokovin <rycarok@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.33.3"
assert_cmd = "1.0.1"
predicates = "1.0.5"